<?php
/**
 * Theme bootstrap for Bliźniak w Smereku.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'BWS_THEME_VERSION', '1.0.0' );
define( 'BWS_THEME_DIR', get_template_directory() );
define( 'BWS_THEME_URI', get_template_directory_uri() );

/**
 * Basic theme setup.
 */
function bws_theme_setup() {
	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support(
		'html5',
		array(
			'search-form',
			'comment-form',
			'comment-list',
			'gallery',
			'caption',
			'script',
			'style',
		)
	);

	add_image_size( 'bws_gallery', 1600, 1200, false );
}
add_action( 'after_setup_theme', 'bws_theme_setup' );

/**
 * Helper to pick latest hashed asset generated by Vite.
 *
 * @param string $pattern Glob pattern relative to /assets.
 */
function bws_find_asset( $pattern ) {
	$files = glob( BWS_THEME_DIR . '/assets/' . $pattern );

	if ( empty( $files ) ) {
		return null;
	}

	usort(
		$files,
		static function ( $a, $b ) {
			return filemtime( $b ) <=> filemtime( $a );
		}
	);

	return basename( $files[0] );
}

/**
 * Enqueue compiled CSS/JS and theme helpers.
 */
function bws_enqueue_assets() {
	$css = bws_find_asset( 'index-*.css' );
	if ( $css ) {
		$css_path = BWS_THEME_DIR . '/assets/' . $css;
		wp_enqueue_style( 'bws-main', BWS_THEME_URI . '/assets/' . $css, array(), filemtime( $css_path ) );
	}

	$custom_css = BWS_THEME_DIR . '/assets/css/theme.css';
	if ( file_exists( $custom_css ) ) {
		wp_enqueue_style( 'bws-theme', BWS_THEME_URI . '/assets/css/theme.css', array( 'bws-main' ), filemtime( $custom_css ) );
	}

	$js = bws_find_asset( 'index-*.js' );
	if ( $js ) {
		$js_path = BWS_THEME_DIR . '/assets/' . $js;
		wp_enqueue_script( 'bws-main', BWS_THEME_URI . '/assets/' . $js, array(), filemtime( $js_path ), true );
		wp_script_add_data( 'bws-main', 'defer', true );
	}

	$theme_js = BWS_THEME_DIR . '/assets/js/theme.js';
	if ( file_exists( $theme_js ) ) {
		wp_enqueue_script( 'bws-theme', BWS_THEME_URI . '/assets/js/theme.js', array(), filemtime( $theme_js ), true );
		wp_script_add_data( 'bws-theme', 'defer', true );
		wp_localize_script(
			'bws-theme',
			'bwsTheme',
			array(
				'headerOffset'   => 96,
				'scrollDuration' => 400,
				'contactAnchor'  => '#kontakt',
			)
		);
	}
}
add_action( 'wp_enqueue_scripts', 'bws_enqueue_assets' );

/**
 * Customizer options.
 */
function bws_customize_register( $wp_customize ) {
	$section = 'bws_settings';

	$wp_customize->add_section(
		$section,
		array(
			'title'       => 'Bliźniak w Smereku – Ustawienia',
			'description' => 'Ustaw treści landing page.',
			'priority'    => 30,
		)
	);

	$fields = array(
		'brand_name'      => array(
			'label'    => 'Nazwa / brand',
			'default'  => 'Bliźniak w Smereku',
			'sanitize' => 'sanitize_text_field',
		),
		'hero_title'      => array(
			'label'    => 'Hero — tytuł',
			'default'  => 'Bliźniak w Smereku — rodzinny wypoczynek w Bieszczadach',
			'sanitize' => 'sanitize_text_field',
		),
		'hero_lead'       => array(
			'label'    => 'Hero — lead',
			'default'  => 'Połówka domu na wyłączność. Do 5 osób + 2 miejsca na narożniku w salonie. Kominek, 2 łazienki, kuchnia, altana z grillem. Wi-Fi i parking w cenie.',
			'sanitize' => 'wp_kses_post',
		),
		'price'           => array(
			'label'    => 'Cena',
			'default'  => '450 zł / doba',
			'sanitize' => 'sanitize_text_field',
		),
		'address'         => array(
			'label'    => 'Adres',
			'default'  => 'Smerek 79, Bieszczady',
			'sanitize' => 'sanitize_text_field',
		),
		'phone'           => array(
			'label'    => 'Telefon',
			'default'  => '+48 514 995 497',
			'sanitize' => 'sanitize_text_field',
		),
		'whatsapp'        => array(
			'label'    => 'WhatsApp',
			'default'  => '+48 514 995 497',
			'sanitize' => 'sanitize_text_field',
		),
		'rules'           => array(
			'label'    => 'Zasady (krótko)',
			'default'  => 'Miejsce dla osób szukających spokoju — bez imprez.',
			'sanitize' => 'wp_kses_post',
		),
		'animals'         => array(
			'label'    => 'Zwierzęta',
			'default'  => 'Zwierzęta dozwolone, mile widziane 🐾',
			'sanitize' => 'wp_kses_post',
		),
		'layout_desc'     => array(
			'label'    => 'Opis układu domu',
			'default'  => 'Przestronne wnętrza na dwóch poziomach — idealne dla rodziny. Do 5 osób + 2 miejsca na narożniku w salonie.',
			'sanitize' => 'wp_kses_post',
		),
		'location_desc'   => array(
			'label'    => 'Opis lokalizacji',
			'default'  => 'Smerek to malownicza wioska u podnóża Połoniny Wetlińskiej. Świetna baza wypadowa na bieszczadzkie szlaki i spokojny wypoczynek.',
			'sanitize' => 'wp_kses_post',
		),
		'maps_link'       => array(
			'label'    => 'Link do Google Maps',
			'default'  => 'https://www.google.com/maps/search/?api=1&query=Smerek+79+Bieszczady',
			'sanitize' => 'esc_url_raw',
		),
	);

	foreach ( $fields as $key => $field ) {
		$wp_customize->add_setting(
			"bws_{$key}",
			array(
				'default'           => $field['default'],
				'sanitize_callback' => $field['sanitize'],
			)
		);

		$wp_customize->add_control(
			"bws_{$key}",
			array(
				'label'   => $field['label'],
				'section' => $section,
				'type'    => 'textarea' === $field['sanitize'] || 'wp_kses_post' === $field['sanitize'] ? 'textarea' : 'text',
			)
		);
	}

	$wp_customize->add_setting(
		'bws_hero_image',
		array(
			'default'           => '',
			'sanitize_callback' => 'absint',
		)
	);

	$wp_customize->add_control(
		new WP_Customize_Media_Control(
			$wp_customize,
			'bws_hero_image',
			array(
				'label'      => 'Obraz HERO',
				'section'    => $section,
				'mime_type'  => 'image',
				'button_labels' => array(
					'select'       => __( 'Wybierz obraz', 'blizniak-smerek' ),
					'change'       => __( 'Zmień obraz', 'blizniak-smerek' ),
					'remove'       => __( 'Usuń', 'blizniak-smerek' ),
					'default'      => __( 'Domyślny', 'blizniak-smerek' ),
					'placeholder'  => __( 'Brak wybranego obrazu', 'blizniak-smerek' ),
					'frame_title'  => __( 'Wybierz lub wgraj', 'blizniak-smerek' ),
					'frame_button' => __( 'Użyj obrazu', 'blizniak-smerek' ),
				),
			)
		)
	);
}
add_action( 'customize_register', 'bws_customize_register' );

/**
 * Quick helper for theme mods with defaults.
 */
function bws_get_mod( $key, $default = '' ) {
	return get_theme_mod( "bws_{$key}", $default );
}

/**
 * Gallery CPT + taxonomy.
 */
function bws_register_gallery_cpt() {
	register_post_type(
		'bs_photo',
		array(
			'labels' => array(
				'name'          => 'Galeria',
				'singular_name' => 'Zdjęcie',
				'add_new_item'  => 'Dodaj zdjęcie do galerii',
				'edit_item'     => 'Edytuj zdjęcie',
			),
			'public'       => true,
			'has_archive'  => false,
			'show_in_rest' => true,
			'menu_icon'    => 'dashicons-format-gallery',
			'supports'     => array( 'title', 'thumbnail' ),
			'rewrite'      => array( 'slug' => 'galeria' ),
		)
	);

	register_taxonomy(
		'bs_photo_category',
		'bs_photo',
		array(
			'labels'            => array(
				'name'          => 'Kategorie galerii',
				'singular_name' => 'Kategoria galerii',
			),
			'hierarchical'      => true,
			'show_admin_column' => true,
			'show_in_rest'      => true,
			'rewrite'           => array( 'slug' => 'bs-photo-category' ),
		)
	);
}
add_action( 'init', 'bws_register_gallery_cpt' );

/**
 * Seed default gallery categories used by filters.
 */
function bws_seed_gallery_terms() {
	$terms = array(
		'salon'    => 'Salon i kominek',
		'kuchnia'  => 'Kuchnia i jadalnia',
		'pokoje'   => 'Pokoje',
		'lazienki' => 'Łazienki',
		'altana'   => 'Altana i grill',
		'okolica'  => 'Okolica i szlaki',
		'taras'    => 'Taras (wkrótce)',
	);

	foreach ( $terms as $slug => $label ) {
		if ( ! term_exists( $slug, 'bs_photo_category' ) ) {
			wp_insert_term(
				$label,
				'bs_photo_category',
				array(
					'slug' => $slug,
				)
			);
		}
	}
}
add_action( 'after_switch_theme', 'bws_seed_gallery_terms' );

/**
 * Contact form handler: nonce + honeypot + wp_mail.
 */
function bws_handle_contact_form() {
	if ( ! is_front_page() || 'POST' !== $_SERVER['REQUEST_METHOD'] ) {
		return;
	}

	$redirect = get_option( 'page_on_front' ) ? get_permalink( (int) get_option( 'page_on_front' ) ) : home_url( '/' );
	$redirect = add_query_arg( 'sent', '0', $redirect );

	if ( empty( $_POST['bws_contact_nonce'] ) || ! wp_verify_nonce( wp_unslash( $_POST['bws_contact_nonce'] ), 'bws_contact_form' ) ) {
		wp_safe_redirect( $redirect );
		exit;
	}

	$honeypot  = ! empty( $_POST['bws_hp'] );
	$name      = isset( $_POST['bws_name'] ) ? sanitize_text_field( wp_unslash( $_POST['bws_name'] ) ) : '';
	$phone     = isset( $_POST['bws_phone'] ) ? sanitize_text_field( wp_unslash( $_POST['bws_phone'] ) ) : '';
	$date_from = isset( $_POST['bws_date_from'] ) ? sanitize_text_field( wp_unslash( $_POST['bws_date_from'] ) ) : '';
	$date_to   = isset( $_POST['bws_date_to'] ) ? sanitize_text_field( wp_unslash( $_POST['bws_date_to'] ) ) : '';
	$guests    = isset( $_POST['bws_guests'] ) ? sanitize_text_field( wp_unslash( $_POST['bws_guests'] ) ) : '';
	$has_pet   = ! empty( $_POST['bws_pet'] );
	$message   = isset( $_POST['bws_message'] ) ? wp_kses_post( wp_unslash( $_POST['bws_message'] ) ) : '';

	if ( $honeypot || empty( $name ) || empty( $phone ) || empty( $date_from ) || empty( $date_to ) || empty( $guests ) ) {
		wp_safe_redirect( $redirect );
		exit;
	}

	$brand   = bws_get_mod( 'brand_name', 'Bliźniak w Smereku' );
	$subject = sprintf( 'Zapytanie z %s', $brand );

	$body  = "Imię: {$name}\n";
	$body .= "Telefon: {$phone}\n";
	$body .= "Termin: {$date_from} - {$date_to}\n";
	$body .= "Liczba osób: {$guests}\n";
	$body .= 'Zwierzę: ' . ( $has_pet ? 'tak' : 'nie' ) . "\n\n";
	if ( ! empty( $message ) ) {
		$body .= "Wiadomość:\n{$message}\n\n";
	}
	$body .= 'Wysłane ze strony: ' . home_url();

	$sent = wp_mail( get_option( 'admin_email' ), $subject, $body );

	$redirect = add_query_arg( 'sent', $sent ? '1' : '0', $redirect );
	wp_safe_redirect( $redirect );
	exit;
}
add_action( 'template_redirect', 'bws_handle_contact_form' );
